// GENERATED by scripts/generate-meme-corpus.mjs — do not edit by hand.
// 122 original in-house meme cards. Nothing scraped, nothing licensed,
// every caption written for cultured and tagged with the Resonance taxonomy.

import type { SeedMeme } from './types';

export const SEED_MEMES: readonly SeedMeme[] = [
  {
    "id": "mk001",
    "topic": "work",
    "text": "me: i’ll just patch one small thing\n\nthe codebase: a nature documentary",
    "alt": "absurd meme card reading: me: i’ll just patch one small thing, the codebase: a nature documentary",
    "tags": [
      "absurd",
      "work_horror",
      "text_post",
      "self_defeating"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 208,
    "laughs": 212
  },
  {
    "id": "mk002",
    "topic": "work",
    "text": "standup meeting:\n\n*agenda: no agenda*",
    "alt": "deadpan meme card reading: standup meeting:, *agenda: no agenda*",
    "tags": [
      "deadpan",
      "observational",
      "text_post",
      "reaction_meme",
      "self_defeating"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 639,
    "laughs": 443
  },
  {
    "id": "mk003",
    "topic": "work",
    "text": "“quick question” — 45 minutes later",
    "alt": "hyperbole meme card reading: “quick question” — 45 minutes later",
    "tags": [
      "hyperbole",
      "observational",
      "text_post",
      "self_defeating"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 274,
    "laughs": 630
  },
  {
    "id": "mk004",
    "topic": "work",
    "text": "my calendar is full but nothing is booked",
    "alt": "absurd meme card reading: my calendar is full but nothing is booked",
    "tags": [
      "absurd",
      "observational",
      "text_post",
      "self_defeating"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 705,
    "laughs": 161
  },
  {
    "id": "mk005",
    "topic": "work",
    "text": "the deploy is green. i am not.",
    "alt": "dark meme card reading: the deploy is green. i am not.",
    "tags": [
      "dark",
      "work_horror",
      "reaction_meme",
      "self_defeating"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 888,
    "laughs": 44
  },
  {
    "id": "mk006",
    "topic": "work",
    "text": "nobody: absolutely nobody:\n\nme at 4:59pm: one more fix",
    "alt": "absurd meme card reading: nobody: absolutely nobody:, me at 4:59pm: one more fix",
    "tags": [
      "absurd",
      "relatable",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 479,
    "laughs": 635
  },
  {
    "id": "mk007",
    "topic": "work",
    "text": "we solved it with a spreadsheet\n\nthe spreadsheet had a bug",
    "alt": "wordplay meme card reading: we solved it with a spreadsheet, the spreadsheet had a bug",
    "tags": [
      "wordplay",
      "edgelord",
      "text_post",
      "affiliative"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 562,
    "laughs": 66
  },
  {
    "id": "mk008",
    "topic": "work",
    "text": "“it works on my machine” is not a defence, it is a confession",
    "alt": "deadpan meme card reading: “it works on my machine” is not a defence, it is a confession",
    "tags": [
      "deadpan",
      "edgelord",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 545,
    "laughs": 49
  },
  {
    "id": "mk009",
    "topic": "work",
    "text": "onboarding doc: 4 pages\n\nactual onboarding: “ask Ravi”",
    "alt": "relatable meme card reading: onboarding doc: 4 pages, actual onboarding: “ask Ravi”",
    "tags": [
      "relatable",
      "observational",
      "screenshot",
      "text_post",
      "self_defeating"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 844,
    "laughs": 448
  },
  {
    "id": "mk010",
    "topic": "work",
    "text": "promotion criteria: be visible\n\nactual criteria: be in the meeting where decisions happen",
    "alt": "edgelord meme card reading: promotion criteria: be visible, actual criteria: be in the meeting where decisions happen",
    "tags": [
      "edgelord",
      "observational",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 822,
    "laughs": 126
  },
  {
    "id": "mk011",
    "topic": "work",
    "text": "i renamed a variable and two things broke\n\nthey were unrelated",
    "alt": "absurd meme card reading: i renamed a variable and two things broke, they were unrelated",
    "tags": [
      "absurd",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 287,
    "laughs": 243
  },
  {
    "id": "mk012",
    "topic": "work",
    "text": "the ticket says “simple”\n\nthe ticket has 14 subtasks",
    "alt": "work horror meme card reading: the ticket says “simple”, the ticket has 14 subtasks",
    "tags": [
      "work_horror",
      "hyperbole",
      "screenshot",
      "self_defeating"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 756,
    "laughs": 712
  },
  {
    "id": "mk013",
    "topic": "work",
    "text": "“can we make it simpler”\n\n*deletes the feature*",
    "alt": "cringe irony meme card reading: “can we make it simpler”, *deletes the feature*",
    "tags": [
      "cringe_irony",
      "work_horror",
      "two_panel",
      "self_defeating"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 573,
    "laughs": 129
  },
  {
    "id": "mk014",
    "topic": "work",
    "text": "writing documentation for future me\n\nfuture me: who is this",
    "alt": "absurd meme card reading: writing documentation for future me, future me: who is this",
    "tags": [
      "absurd",
      "meta",
      "text_post",
      "self_defeating"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 650,
    "laughs": 506
  },
  {
    "id": "mk015",
    "topic": "work",
    "text": "friday deploy at 4:58\n\nit is always friday at 4:58",
    "alt": "absurd meme card reading: friday deploy at 4:58, it is always friday at 4:58",
    "tags": [
      "absurd",
      "relatable",
      "reaction_meme",
      "self_defeating"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 507,
    "laughs": 411
  },
  {
    "id": "mk016",
    "topic": "work",
    "text": "i have opinions about tabs vs spaces\n\ni will not be changing them",
    "alt": "edgelord meme card reading: i have opinions about tabs vs spaces, i will not be changing them",
    "tags": [
      "edgelord",
      "wordplay",
      "text_post",
      "aggressive"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 916,
    "laughs": 520
  },
  {
    "id": "mk017",
    "topic": "music",
    "text": "“one more song then bed”\n\nme at 4am: sequencing a second album",
    "alt": "relatable meme card reading: “one more song then bed”, me at 4am: sequencing a second album",
    "tags": [
      "relatable",
      "dark",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 285,
    "laughs": 389
  },
  {
    "id": "mk018",
    "topic": "music",
    "text": "the 8 seconds before the beat drop\n\nme: 🧍",
    "alt": "absurd meme card reading: the 8 seconds before the beat drop, me: 🧍",
    "tags": [
      "absurd",
      "reaction_meme",
      "self_defeating"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 302,
    "laughs": 406
  },
  {
    "id": "mk019",
    "topic": "music",
    "text": "new album friday at midnight\n\nme: refreshing at 11:59 like a raccoon",
    "alt": "relatable meme card reading: new album friday at midnight, me: refreshing at 11:59 like a raccoon",
    "tags": [
      "relatable",
      "hyperbole",
      "text_post",
      "affiliative"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 551,
    "laughs": 707
  },
  {
    "id": "mk020",
    "topic": "music",
    "text": "i can tell you the tempo of a song by vibe alone\n\nit is almost always wrong",
    "alt": "wordplay meme card reading: i can tell you the tempo of a song by vibe alone, it is almost always wrong",
    "tags": [
      "wordplay",
      "deadpan",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 819,
    "laughs": 223
  },
  {
    "id": "mk021",
    "topic": "music",
    "text": "the bridge. THE BRIDGE.\n\ni have no one to send this to. i am sending it here.",
    "alt": "hyperbole meme card reading: the bridge. THE BRIDGE., i have no one to send this to. i am sending it here.",
    "tags": [
      "hyperbole",
      "niche_hobby",
      "text_post",
      "affiliative"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 62,
    "laughs": 318
  },
  {
    "id": "mk022",
    "topic": "music",
    "text": "“it grows on you” is what we say\n\nabout the song we skipped 40 times",
    "alt": "wordplay meme card reading: “it grows on you” is what we say, about the song we skipped 40 times",
    "tags": [
      "wordplay",
      "deadpan",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 713,
    "laughs": 717
  },
  {
    "id": "mk023",
    "topic": "music",
    "text": "vinyl arrived today\n\nnow i own a music player and one album",
    "alt": "niche hobby meme card reading: vinyl arrived today, now i own a music player and one album",
    "tags": [
      "niche_hobby",
      "wholesome",
      "text_post",
      "affiliative"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 896,
    "laughs": 600
  },
  {
    "id": "mk024",
    "topic": "music",
    "text": "my taste in music peaked in 2019\n\nand honestly? valid",
    "alt": "boomer meme card reading: my taste in music peaked in 2019, and honestly? valid",
    "tags": [
      "boomer",
      "self_defeating",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 267,
    "laughs": 323
  },
  {
    "id": "mk025",
    "topic": "music",
    "text": "the song is 3 minutes long\n\nthe epilogue is 3 days long",
    "alt": "hyperbole meme card reading: the song is 3 minutes long, the epilogue is 3 days long",
    "tags": [
      "hyperbole",
      "dark",
      "text_post",
      "self_enhancing"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 918,
    "laughs": 22
  },
  {
    "id": "mk026",
    "topic": "music",
    "text": "someone played this at a party\n\ni have been emotionally bonded since",
    "alt": "relatable meme card reading: someone played this at a party, i have been emotionally bonded since",
    "tags": [
      "relatable",
      "niche_hobby",
      "text_post",
      "affiliative"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 553,
    "laughs": 209
  },
  {
    "id": "mk027",
    "topic": "music",
    "text": "rewind credits: 4\n\nused on: finding the exact second the drums enter",
    "alt": "niche hobby meme card reading: rewind credits: 4, used on: finding the exact second the drums enter",
    "tags": [
      "niche_hobby",
      "absurd",
      "screenshot",
      "self_defeating"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 284,
    "laughs": 340
  },
  {
    "id": "mk028",
    "topic": "music",
    "text": "discovered this song from a 14-second clip\n\nand now the full version owns me",
    "alt": "relatable meme card reading: discovered this song from a 14-second clip, and now the full version owns me",
    "tags": [
      "relatable",
      "niche_hobby",
      "text_post",
      "affiliative"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 691,
    "laughs": 595
  },
  {
    "id": "mk029",
    "topic": "music",
    "text": "i make a playlist for every mood\n\nthe mood is always “avoidant on a tuesday”",
    "alt": "self defeating meme card reading: i make a playlist for every mood, the mood is always “avoidant on a tuesday”",
    "tags": [
      "self_defeating",
      "dark",
      "text_post",
      "self_defeating"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 442,
    "laughs": 598
  },
  {
    "id": "mk030",
    "topic": "music",
    "text": "the key change is illegal in 11 states\n\ni know because i checked, in a group chat",
    "alt": "wordplay meme card reading: the key change is illegal in 11 states, i know because i checked, in a group chat",
    "tags": [
      "wordplay",
      "niche_hobby",
      "text_post",
      "affiliative"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 168,
    "laughs": 172
  },
  {
    "id": "mk031",
    "topic": "music",
    "text": "concert: 3 songs in and everyone is filming\n\nme: finally hearing the second song",
    "alt": "observational meme card reading: concert: 3 songs in and everyone is filming, me: finally hearing the second song",
    "tags": [
      "observational",
      "cringe_irony",
      "two_panel",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 769,
    "laughs": 473
  },
  {
    "id": "mk032",
    "topic": "music",
    "text": "“this is so niche”\n\nme, streaming it on loop: correct",
    "alt": "niche hobby meme card reading: “this is so niche”, me, streaming it on loop: correct",
    "tags": [
      "niche_hobby",
      "affiliative",
      "text_post",
      "self_enhancing"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 234,
    "laughs": 590
  },
  {
    "id": "mk033",
    "topic": "music",
    "text": "the bassline does not resolve\n\nand that is the whole point",
    "alt": "deadpan meme card reading: the bassline does not resolve, and that is the whole point",
    "tags": [
      "deadpan",
      "niche_hobby",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 659,
    "laughs": 63
  },
  {
    "id": "mk034",
    "topic": "music",
    "text": "my most played song this year starts with rain",
    "alt": "wholesome meme card reading: my most played song this year starts with rain",
    "tags": [
      "wholesome",
      "niche_hobby",
      "text_post",
      "affiliative"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 908,
    "laughs": 364
  },
  {
    "id": "mk035",
    "topic": "music",
    "text": "i cannot sing. i will never sing.\nyou will hear me singing.",
    "alt": "self defeating meme card reading: i cannot sing. i will never sing., you will hear me singing.",
    "tags": [
      "self_defeating",
      "affiliative",
      "two_panel",
      "self_defeating"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 725,
    "laughs": 481
  },
  {
    "id": "mk036",
    "topic": "screen",
    "text": "“just one more episode”\n\nsunrise: hi",
    "alt": "relatable meme card reading: “just one more episode”, sunrise: hi",
    "tags": [
      "relatable",
      "dark",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 74,
    "laughs": 478
  },
  {
    "id": "mk037",
    "topic": "screen",
    "text": "starting season 1 at 1am is a lifestyle choice",
    "alt": "dark meme card reading: starting season 1 at 1am is a lifestyle choice",
    "tags": [
      "dark",
      "relatable",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 439,
    "laughs": 595
  },
  {
    "id": "mk038",
    "topic": "screen",
    "text": "“it gets good at episode 12”\n\nepisode 3: nothing could be worse\n\nepisode 12: nothing could be better",
    "alt": "hyperbole meme card reading: “it gets good at episode 12”, episode 3: nothing could be worse, episode 12: nothing could be better",
    "tags": [
      "hyperbole",
      "wordplay",
      "text_post",
      "self_defeating"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 432,
    "laughs": 636
  },
  {
    "id": "mk039",
    "topic": "screen",
    "text": "finished the show. now what.\n\nthe void stares back",
    "alt": "dark meme card reading: finished the show. now what., the void stares back",
    "tags": [
      "dark",
      "absurd",
      "reaction_meme",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 249,
    "laughs": 53
  },
  {
    "id": "mk040",
    "topic": "screen",
    "text": "streaming service suggested this because i paused once, twice, three times",
    "alt": "absurd meme card reading: streaming service suggested this because i paused once, twice, three times",
    "tags": [
      "absurd",
      "cringe_irony",
      "screenshot",
      "self_defeating"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 841,
    "laughs": 697
  },
  {
    "id": "mk041",
    "topic": "screen",
    "text": "rewatching the comfort show for the 900th time\n\nstill know every line",
    "alt": "wholesome meme card reading: rewatching the comfort show for the 900th time, still know every line",
    "tags": [
      "wholesome",
      "relatable",
      "text_post",
      "affiliative"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 124,
    "laughs": 580
  },
  {
    "id": "mk042",
    "topic": "screen",
    "text": "the plot is simple:\n\n1. someone lies\n2. everyone forgives them",
    "alt": "deadpan meme card reading: the plot is simple:, 1. someone lies, 2. everyone forgives them",
    "tags": [
      "deadpan",
      "observational",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 555,
    "laughs": 111
  },
  {
    "id": "mk043",
    "topic": "screen",
    "text": "i paused to check the fridge and now\n\nseven episodes passed",
    "alt": "absurd meme card reading: i paused to check the fridge and now, seven episodes passed",
    "tags": [
      "absurd",
      "relatable",
      "reaction_meme",
      "self_defeating"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 190,
    "laughs": 694
  },
  {
    "id": "mk044",
    "topic": "screen",
    "text": "season finale, alone, at 1am, in the dark.\n\nthis is cinema and i accept that.",
    "alt": "wholesome meme card reading: season finale, alone, at 1am, in the dark., this is cinema and i accept that.",
    "tags": [
      "wholesome",
      "dark",
      "text_post",
      "affiliative"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 885,
    "laughs": 689
  },
  {
    "id": "mk045",
    "topic": "screen",
    "text": "“canceled after 2 seasons”\n\nwe were not ready anyway",
    "alt": "wordplay meme card reading: “canceled after 2 seasons”, we were not ready anyway",
    "tags": [
      "wordplay",
      "dark",
      "text_post",
      "self_defeating"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 284,
    "laughs": 388
  },
  {
    "id": "mk046",
    "topic": "screen",
    "text": "adding 400 hours of background noise to my personality",
    "alt": "self defeating meme card reading: adding 400 hours of background noise to my personality",
    "tags": [
      "self_defeating",
      "meta",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 775,
    "laughs": 279
  },
  {
    "id": "mk047",
    "topic": "screen",
    "text": "i watch documentaries about my own habits\n\nand then do the habits",
    "alt": "observational meme card reading: i watch documentaries about my own habits, and then do the habits",
    "tags": [
      "observational",
      "meta",
      "text_post",
      "self_defeating"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 350,
    "laughs": 106
  },
  {
    "id": "mk048",
    "topic": "screen",
    "text": "binge-watched a cooking show\n\nstill cannot cook",
    "alt": "absurd meme card reading: binge-watched a cooking show, still cannot cook",
    "tags": [
      "absurd",
      "cringe_irony",
      "two_panel",
      "self_defeating"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 713,
    "laughs": 369
  },
  {
    "id": "mk049",
    "topic": "screen",
    "text": "the new season has 3 good episodes\n\nthat is a 100% success rate by industry standards",
    "alt": "deadpan meme card reading: the new season has 3 good episodes, that is a 100% success rate by industry standards",
    "tags": [
      "deadpan",
      "edgelord",
      "text_post",
      "self_defeating"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 896,
    "laughs": 252
  },
  {
    "id": "mk050",
    "topic": "screen",
    "text": "fell asleep mid-scene\n\nwoke up to the credits. no idea who anyone is.",
    "alt": "relatable meme card reading: fell asleep mid-scene, woke up to the credits. no idea who anyone is.",
    "tags": [
      "relatable",
      "absurd",
      "reaction_meme",
      "self_defeating"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 330,
    "laughs": 186
  },
  {
    "id": "mk051",
    "topic": "screen",
    "text": "added a new language because the character speaks it\n\nnow i’m invested. this is a trap.",
    "alt": "niche hobby meme card reading: added a new language because the character speaks it, now i’m invested. this is a trap.",
    "tags": [
      "niche_hobby",
      "wordplay",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 187,
    "laughs": 91
  },
  {
    "id": "mk052",
    "topic": "screen",
    "text": "the prestige TV to match my unhinged schedule",
    "alt": "wordplay meme card reading: the prestige TV to match my unhinged schedule",
    "tags": [
      "wordplay",
      "cringe_irony",
      "text_post",
      "self_enhancing"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 264,
    "laughs": 468
  },
  {
    "id": "mk053",
    "topic": "screen",
    "text": "i finished the series that everyone asked me about\n\nsorry it took 4 years",
    "alt": "deadpan meme card reading: i finished the series that everyone asked me about, sorry it took 4 years",
    "tags": [
      "deadpan",
      "self_defeating",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 81,
    "laughs": 585
  },
  {
    "id": "mk054",
    "topic": "life",
    "text": "gym: 5 min\nstretching: 4 min\nresting on my phone: 51 min",
    "alt": "relatable meme card reading: gym: 5 min, stretching: 4 min, resting on my phone: 51 min",
    "tags": [
      "relatable",
      "wholesome",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 618,
    "laughs": 322
  },
  {
    "id": "mk055",
    "topic": "life",
    "text": "hydration is a lifestyle now",
    "alt": "absurd meme card reading: hydration is a lifestyle now",
    "tags": [
      "absurd",
      "self_defeating",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 535,
    "laughs": 191
  },
  {
    "id": "mk056",
    "topic": "life",
    "text": "my dog hears the word “walk” from three rooms away\n\ni hear the word “out” from three words away",
    "alt": "wholesome meme card reading: my dog hears the word “walk” from three rooms away, i hear the word “out” from three words away",
    "tags": [
      "wholesome",
      "relatable",
      "text_post",
      "affiliative"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 552,
    "laughs": 208
  },
  {
    "id": "mk057",
    "topic": "life",
    "text": "cooking for one is just meal prep\n\nwith nobody to impress",
    "alt": "observational meme card reading: cooking for one is just meal prep, with nobody to impress",
    "tags": [
      "observational",
      "wholesome",
      "text_post",
      "affiliative"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 253,
    "laughs": 509
  },
  {
    "id": "mk058",
    "topic": "life",
    "text": "the smoke alarm has opinions about my cooking\n\nwe are in a relationship now",
    "alt": "absurd meme card reading: the smoke alarm has opinions about my cooking, we are in a relationship now",
    "tags": [
      "absurd",
      "wordplay",
      "text_post",
      "self_defeating"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 710,
    "laughs": 466
  },
  {
    "id": "mk059",
    "topic": "life",
    "text": "plants: thriving\n\nme: thriving, technically",
    "alt": "wholesome meme card reading: plants: thriving, me: thriving, technically",
    "tags": [
      "wholesome",
      "self_defeating",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 59,
    "laughs": 463
  },
  {
    "id": "mk060",
    "topic": "life",
    "text": "i go outside “for a bit”\n\nthe sun has fully retired by then",
    "alt": "relatable meme card reading: i go outside “for a bit”, the sun has fully retired by then",
    "tags": [
      "relatable",
      "dark",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 223,
    "laughs": 679
  },
  {
    "id": "mk061",
    "topic": "life",
    "text": "the corner of the shop where the good snacks are\n\nnobody goes there. it is mine.",
    "alt": "niche hobby meme card reading: the corner of the shop where the good snacks are, nobody goes there. it is mine.",
    "tags": [
      "niche_hobby",
      "wholesome",
      "text_post",
      "affiliative"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 78,
    "laughs": 682
  },
  {
    "id": "mk062",
    "topic": "life",
    "text": "weekend plans: aggressively unplanned\n\nand that is the whole point",
    "alt": "relatable meme card reading: weekend plans: aggressively unplanned, and that is the whole point",
    "tags": [
      "relatable",
      "absurd",
      "text_post",
      "self_defeating"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 553,
    "laughs": 509
  },
  {
    "id": "mk063",
    "topic": "life",
    "text": "laundry day is a personality trait at this point",
    "alt": "observational meme card reading: laundry day is a personality trait at this point",
    "tags": [
      "observational",
      "deadpan",
      "text_post",
      "self_defeating"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 632,
    "laughs": 88
  },
  {
    "id": "mk064",
    "topic": "life",
    "text": "bought a plant to prove i am responsible\n\nthe plant is thriving. i am not.",
    "alt": "wordplay meme card reading: bought a plant to prove i am responsible, the plant is thriving. i am not.",
    "tags": [
      "wordplay",
      "self_defeating",
      "two_panel",
      "self_defeating"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 487,
    "laughs": 91
  },
  {
    "id": "mk065",
    "topic": "life",
    "text": "my idea of adventure: a different route home",
    "alt": "relatable meme card reading: my idea of adventure: a different route home",
    "tags": [
      "relatable",
      "absurd",
      "text_post",
      "self_defeating"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 918,
    "laughs": 674
  },
  {
    "id": "mk066",
    "topic": "life",
    "text": "walking to get milk takes 4 minutes\n\ncoming back takes 22",
    "alt": "hyperbole meme card reading: walking to get milk takes 4 minutes, coming back takes 22",
    "tags": [
      "hyperbole",
      "relatable",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 773,
    "laughs": 677
  },
  {
    "id": "mk067",
    "topic": "life",
    "text": "i reorganized my bookmarks by mood\n\nnow i have 3,000 bookmarks and 12 moods",
    "alt": "niche hobby meme card reading: i reorganized my bookmarks by mood, now i have 3,000 bookmarks and 12 moods",
    "tags": [
      "niche_hobby",
      "absurd",
      "screenshot",
      "self_defeating"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 852,
    "laughs": 256
  },
  {
    "id": "mk068",
    "topic": "life",
    "text": "the third cup of coffee has left the building",
    "alt": "absurd meme card reading: the third cup of coffee has left the building",
    "tags": [
      "absurd",
      "self_defeating",
      "reaction_meme",
      "self_defeating"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 63,
    "laughs": 519
  },
  {
    "id": "mk069",
    "topic": "life",
    "text": "made a pasta from scratch\n\nso did the sauce from a jar. still counts.",
    "alt": "wordplay meme card reading: made a pasta from scratch, so did the sauce from a jar. still counts.",
    "tags": [
      "wordplay",
      "self_defeating",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 494,
    "laughs": 98
  },
  {
    "id": "mk070",
    "topic": "life",
    "text": "sunday scaries vs sunday scaries: late edition",
    "alt": "wordplay meme card reading: sunday scaries vs sunday scaries: late edition",
    "tags": [
      "wordplay",
      "relatable",
      "text_post",
      "self_defeating"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 728,
    "laughs": 684
  },
  {
    "id": "mk071",
    "topic": "life",
    "text": "i hold doorways like it is my job",
    "alt": "wholesome meme card reading: i hold doorways like it is my job",
    "tags": [
      "wholesome",
      "cringe_irony",
      "text_post",
      "affiliative"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 429,
    "laughs": 285
  },
  {
    "id": "mk072",
    "topic": "love",
    "text": "flirting style: sending a song at 1:47am\n\ncaption: “no reason”",
    "alt": "romance disaster meme card reading: flirting style: sending a song at 1:47am, caption: “no reason”",
    "tags": [
      "romance_disaster",
      "relatable",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 286,
    "laughs": 190
  },
  {
    "id": "mk073",
    "topic": "love",
    "text": "we have not spoken in 6 weeks\n\nbut the playlist is still collaborative",
    "alt": "romance disaster meme card reading: we have not spoken in 6 weeks, but the playlist is still collaborative",
    "tags": [
      "romance_disaster",
      "wordplay",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 651,
    "laughs": 307
  },
  {
    "id": "mk074",
    "topic": "love",
    "text": "“we should hang out sometime”\n\ntransmission received. never acknowledged.",
    "alt": "deadpan meme card reading: “we should hang out sometime”, transmission received. never acknowledged.",
    "tags": [
      "deadpan",
      "romance_disaster",
      "text_post",
      "self_defeating"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 380,
    "laughs": 584
  },
  {
    "id": "mk075",
    "topic": "love",
    "text": "the read receipt is on and it is a hostage situation",
    "alt": "dark meme card reading: the read receipt is on and it is a hostage situation",
    "tags": [
      "dark",
      "romance_disaster",
      "reaction_meme",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 81,
    "laughs": 185
  },
  {
    "id": "mk076",
    "topic": "love",
    "text": "they replied “haha” and i have not recovered",
    "alt": "romance disaster meme card reading: they replied “haha” and i have not recovered",
    "tags": [
      "romance_disaster",
      "cringe_irony",
      "text_post",
      "self_defeating"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 446,
    "laughs": 302
  },
  {
    "id": "mk077",
    "topic": "love",
    "text": "my type: person with good taste and terrible timing",
    "alt": "romance disaster meme card reading: my type: person with good taste and terrible timing",
    "tags": [
      "romance_disaster",
      "wordplay",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 363,
    "laughs": 567
  },
  {
    "id": "mk078",
    "topic": "love",
    "text": "confidently single. aggressively coupled to my spotify.",
    "alt": "wordplay meme card reading: confidently single. aggressively coupled to my spotify.",
    "tags": [
      "wordplay",
      "self_enhancing",
      "text_post",
      "self_enhancing"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 856,
    "laughs": 312
  },
  {
    "id": "mk079",
    "topic": "love",
    "text": "crush archive: songs i sent to no one",
    "alt": "self defeating meme card reading: crush archive: songs i sent to no one",
    "tags": [
      "self_defeating",
      "romance_disaster",
      "screenshot",
      "self_defeating"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 557,
    "laughs": 613
  },
  {
    "id": "mk080",
    "topic": "love",
    "text": "“let’s keep it chill”\n\nsure. here is a 14-page analysis of your texts.",
    "alt": "romance disaster meme card reading: “let’s keep it chill”, sure. here is a 14-page analysis of your texts.",
    "tags": [
      "romance_disaster",
      "hyperbole",
      "two_panel",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 169,
    "laughs": 173
  },
  {
    "id": "mk081",
    "topic": "love",
    "text": "dating app fatigue: i now swipe through playlists faster than people",
    "alt": "meta meme card reading: dating app fatigue: i now swipe through playlists faster than people",
    "tags": [
      "meta",
      "absurd",
      "text_post",
      "self_defeating"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 800,
    "laughs": 304
  },
  {
    "id": "mk082",
    "topic": "love",
    "text": "situationship: a relationship where both people are correct",
    "alt": "wordplay meme card reading: situationship: a relationship where both people are correct",
    "tags": [
      "wordplay",
      "observational",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 391,
    "laughs": 195
  },
  {
    "id": "mk083",
    "topic": "love",
    "text": "we agreed to be casual\n\nand then I made a shared spreadsheet",
    "alt": "romance disaster meme card reading: we agreed to be casual, and then I made a shared spreadsheet",
    "tags": [
      "romance_disaster",
      "niche_hobby",
      "screenshot",
      "self_defeating"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 534,
    "laughs": 290
  },
  {
    "id": "mk084",
    "topic": "love",
    "text": "the late night text lands at 2:14am\n\nwhich is the worst possible time to be right",
    "alt": "romance disaster meme card reading: the late night text lands at 2:14am, which is the worst possible time to be right",
    "tags": [
      "romance_disaster",
      "dark",
      "reaction_meme",
      "self_defeating"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 457,
    "laughs": 613
  },
  {
    "id": "mk085",
    "topic": "love",
    "text": "“i am bad at texting” \n\n*immediately proves it*",
    "alt": "deadpan meme card reading: “i am bad at texting” , *immediately proves it*",
    "tags": [
      "deadpan",
      "cringe_irony",
      "text_post",
      "self_defeating"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 640,
    "laughs": 496
  },
  {
    "id": "mk086",
    "topic": "love",
    "text": "meeting their friends: performance review: pass",
    "alt": "cringe irony meme card reading: meeting their friends: performance review: pass",
    "tags": [
      "cringe_irony",
      "romance_disaster",
      "text_post",
      "self_enhancing"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 171,
    "laughs": 27
  },
  {
    "id": "mk087",
    "topic": "love",
    "text": "the mutual friend who has to translate for both of us",
    "alt": "romance disaster meme card reading: the mutual friend who has to translate for both of us",
    "tags": [
      "romance_disaster",
      "observational",
      "two_panel",
      "self_defeating"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 706,
    "laughs": 610
  },
  {
    "id": "mk088",
    "topic": "love",
    "text": "they share my exact bad take on a 2014 band\n\nthis is the one. this is the one.",
    "alt": "niche hobby meme card reading: they share my exact bad take on a 2014 band, this is the one. this is the one.",
    "tags": [
      "niche_hobby",
      "affiliative",
      "text_post",
      "affiliative"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 881,
    "laughs": 185
  },
  {
    "id": "mk089",
    "topic": "love",
    "text": "i deleted the app. the memories remain.",
    "alt": "dark meme card reading: i deleted the app. the memories remain.",
    "tags": [
      "dark",
      "romance_disaster",
      "text_post",
      "self_defeating"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 164,
    "laughs": 68
  },
  {
    "id": "mk090",
    "topic": "money",
    "text": "budget review: rent or matcha\n\nmatcha, obviously",
    "alt": "money pain meme card reading: budget review: rent or matcha, matcha, obviously",
    "tags": [
      "money_pain",
      "wordplay",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 166,
    "laughs": 270
  },
  {
    "id": "mk091",
    "topic": "money",
    "text": "“treat yourself”\n\nthe treat: $9 toast and a quiet reckoning",
    "alt": "money pain meme card reading: “treat yourself”, the treat: $9 toast and a quiet reckoning",
    "tags": [
      "money_pain",
      "relatable",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 531,
    "laughs": 387
  },
  {
    "id": "mk092",
    "topic": "money",
    "text": "subscription audit found 6 things\n\ni have used 2 of them",
    "alt": "money pain meme card reading: subscription audit found 6 things, i have used 2 of them",
    "tags": [
      "money_pain",
      "absurd",
      "screenshot",
      "self_defeating"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 40,
    "laughs": 496
  },
  {
    "id": "mk093",
    "topic": "money",
    "text": "payday went: rent, groceries, subscriptions\n\nleaves: a good sandwich and hope",
    "alt": "money pain meme card reading: payday went: rent, groceries, subscriptions, leaves: a good sandwich and hope",
    "tags": [
      "money_pain",
      "relatable",
      "text_post",
      "self_defeating"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 641,
    "laughs": 97
  },
  {
    "id": "mk094",
    "topic": "money",
    "text": "concert tickets: excellent seats\n\nfees: also excellent",
    "alt": "money pain meme card reading: concert tickets: excellent seats, fees: also excellent",
    "tags": [
      "money_pain",
      "hyperbole",
      "text_post",
      "self_defeating"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 326,
    "laughs": 382
  },
  {
    "id": "mk095",
    "topic": "money",
    "text": "the free trial lasted 9 days\n\ni forgot everything from day 3",
    "alt": "absurd meme card reading: the free trial lasted 9 days, i forgot everything from day 3",
    "tags": [
      "absurd",
      "self_defeating",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 575,
    "laughs": 379
  },
  {
    "id": "mk096",
    "topic": "money",
    "text": "delivery fee is a toll on your own groceries",
    "alt": "observational meme card reading: delivery fee is a toll on your own groceries",
    "tags": [
      "observational",
      "money_pain",
      "text_post",
      "self_defeating"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 260,
    "laughs": 664
  },
  {
    "id": "mk097",
    "topic": "money",
    "text": "“it’s an investment in myself”\n\nit is a jacket",
    "alt": "cringe irony meme card reading: “it’s an investment in myself”, it is a jacket",
    "tags": [
      "cringe_irony",
      "money_pain",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 861,
    "laughs": 265
  },
  {
    "id": "mk098",
    "topic": "money",
    "text": "i split the bill to the penny\n\nthen missed the last train anyway",
    "alt": "money pain meme card reading: i split the bill to the penny, then missed the last train anyway",
    "tags": [
      "money_pain",
      "romance_disaster",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 802,
    "laughs": 506
  },
  {
    "id": "mk099",
    "topic": "money",
    "text": "side hustle: buying things cheaper than everyone else",
    "alt": "deadpan meme card reading: side hustle: buying things cheaper than everyone else",
    "tags": [
      "deadpan",
      "money_pain",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 151,
    "laughs": 107
  },
  {
    "id": "mk100",
    "topic": "money",
    "text": "i opened a spreadsheet to save money\n\nthe spreadsheet cost me 3 hours",
    "alt": "money pain meme card reading: i opened a spreadsheet to save money, the spreadsheet cost me 3 hours",
    "tags": [
      "money_pain",
      "niche_hobby",
      "screenshot",
      "self_defeating"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 140,
    "laughs": 144
  },
  {
    "id": "mk101",
    "topic": "money",
    "text": "price tag said “vintage”\n\nit was made last thursday",
    "alt": "cringe irony meme card reading: price tag said “vintage”, it was made last thursday",
    "tags": [
      "cringe_irony",
      "money_pain",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 61,
    "laughs": 565
  },
  {
    "id": "mk102",
    "topic": "money",
    "text": "the group chat has a “who owes who” list\n\nit is 400 messages long",
    "alt": "money pain meme card reading: the group chat has a “who owes who” list, it is 400 messages long",
    "tags": [
      "money_pain",
      "observational",
      "two_panel",
      "self_defeating"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 310,
    "laughs": 166
  },
  {
    "id": "mk103",
    "topic": "money",
    "text": "“it’s an investment”\n\nthe return is one very good t-shirt",
    "alt": "money pain meme card reading: “it’s an investment”, the return is one very good t-shirt",
    "tags": [
      "money_pain",
      "wordplay",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 631,
    "laughs": 35
  },
  {
    "id": "mk104",
    "topic": "money",
    "text": "i budgeted for concert tickets\n\nthe budget had other ideas",
    "alt": "money pain meme card reading: i budgeted for concert tickets, the budget had other ideas",
    "tags": [
      "money_pain",
      "relatable",
      "text_post",
      "self_defeating"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 200,
    "laughs": 456
  },
  {
    "id": "mk105",
    "topic": "money",
    "text": "delivery minimums exist to make you\n\nbuy the thing you did not want",
    "alt": "money pain meme card reading: delivery minimums exist to make you, buy the thing you did not want",
    "tags": [
      "money_pain",
      "observational",
      "text_post",
      "self_defeating"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 801,
    "laughs": 57
  },
  {
    "id": "mk106",
    "topic": "money",
    "text": "a cheap flight to nowhere beats a bus\n\nthis is what personal finance has done to me",
    "alt": "absurd meme card reading: a cheap flight to nowhere beats a bus, this is what personal finance has done to me",
    "tags": [
      "absurd",
      "money_pain",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 266,
    "laughs": 570
  },
  {
    "id": "mk107",
    "topic": "money",
    "text": "my emergency fund is 6 months of instant noodles\n\ngrowth is a process",
    "alt": "money pain meme card reading: my emergency fund is 6 months of instant noodles, growth is a process",
    "tags": [
      "money_pain",
      "wordplay",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 411,
    "laughs": 171
  },
  {
    "id": "mk108",
    "topic": "life",
    "text": "my humour has two settings: charmingly off and deeply concerned",
    "alt": "meta meme card reading: my humour has two settings: charmingly off and deeply concerned",
    "tags": [
      "meta",
      "wordplay",
      "text_post",
      "affiliative"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 624,
    "laughs": 28
  },
  {
    "id": "mk109",
    "topic": "life",
    "text": "the group chat goes quiet whenever i post anything with nuance",
    "alt": "observational meme card reading: the group chat goes quiet whenever i post anything with nuance",
    "tags": [
      "observational",
      "dark",
      "two_panel",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 325,
    "laughs": 25
  },
  {
    "id": "mk110",
    "topic": "life",
    "text": "i rate every restaurant by the song they play at the door",
    "alt": "niche hobby meme card reading: i rate every restaurant by the song they play at the door",
    "tags": [
      "niche_hobby",
      "affiliative",
      "text_post",
      "affiliative"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 755,
    "laughs": 259
  },
  {
    "id": "mk111",
    "topic": "work",
    "text": "confident answer delivered with zero preparation",
    "alt": "cringe irony meme card reading: confident answer delivered with zero preparation",
    "tags": [
      "cringe_irony",
      "wordplay",
      "text_post",
      "aggressive"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 898,
    "laughs": 354
  },
  {
    "id": "mk112",
    "topic": "love",
    "text": "i told them i’d listen to the album\n\ni have listened to the album",
    "alt": "romance disaster meme card reading: i told them i’d listen to the album, i have listened to the album",
    "tags": [
      "romance_disaster",
      "wordplay",
      "text_post",
      "self_defeating"
    ],
    "bg": "#9EC5E8",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 533,
    "laughs": 237
  },
  {
    "id": "mk113",
    "topic": "life",
    "text": "the algorithm finally understood me\n\nit showed me one ad",
    "alt": "absurd meme card reading: the algorithm finally understood me, it showed me one ad",
    "tags": [
      "absurd",
      "meta",
      "text_post",
      "self_defeating"
    ],
    "bg": "#EFE9DA",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 832,
    "laughs": 636
  },
  {
    "id": "mk114",
    "topic": "life",
    "text": "quiet mode off. back to being perceived.",
    "alt": "wordplay meme card reading: quiet mode off. back to being perceived.",
    "tags": [
      "wordplay",
      "wholesome",
      "text_post",
      "affiliative"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 203,
    "laughs": 359
  },
  {
    "id": "mk115",
    "topic": "life",
    "text": "a very sincere meme about cheese got 400 laughs\n\nwe are all just people",
    "alt": "wholesome meme card reading: a very sincere meme about cheese got 400 laughs, we are all just people",
    "tags": [
      "wholesome",
      "absurd",
      "text_post",
      "affiliative"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 738,
    "laughs": 242
  },
  {
    "id": "mk116",
    "topic": "money",
    "text": "i apologise in advance for how i talk about spreadsheets",
    "alt": "niche hobby meme card reading: i apologise in advance for how i talk about spreadsheets",
    "tags": [
      "niche_hobby",
      "self_defeating",
      "text_post",
      "self_defeating"
    ],
    "bg": "#2b2a26",
    "fg": "#EFE9DA",
    "ac": "#ff5d7a",
    "likes": 821,
    "laughs": 677
  },
  {
    "id": "mk117",
    "topic": "music",
    "text": "the only genre i trust is the one that surprises me",
    "alt": "niche hobby meme card reading: the only genre i trust is the one that surprises me",
    "tags": [
      "niche_hobby",
      "affiliative",
      "text_post",
      "self_enhancing"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 104,
    "laughs": 560
  },
  {
    "id": "mk118",
    "topic": "music",
    "text": "hard to explain to someone who has never paused mid-sentence to search a song",
    "alt": "niche hobby meme card reading: hard to explain to someone who has never paused mid-sentence to search a song",
    "tags": [
      "niche_hobby",
      "wordplay",
      "text_post",
      "affiliative"
    ],
    "bg": "#F26B4E",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 627,
    "laughs": 631
  },
  {
    "id": "mk119",
    "topic": "music",
    "text": "they said “put on something”\n\nand i took that as a creative brief",
    "alt": "absurd meme card reading: they said “put on something”, and i took that as a creative brief",
    "tags": [
      "absurd",
      "affiliative",
      "text_post",
      "self_defeating"
    ],
    "bg": "#ff8fa3",
    "fg": "#141413",
    "ac": "#F2D45C",
    "likes": 262,
    "laughs": 118
  },
  {
    "id": "mk120",
    "topic": "screen",
    "text": "three episodes in, i have decided the show is about something else entirely",
    "alt": "absurd meme card reading: three episodes in, i have decided the show is about something else entirely",
    "tags": [
      "absurd",
      "meta",
      "text_post",
      "self_defeating"
    ],
    "bg": "#F2D45C",
    "fg": "#141413",
    "ac": "#141413",
    "likes": 910,
    "laughs": 614
  },
  {
    "id": "mk121",
    "topic": "screen",
    "text": "the confidence of a person who has read the whole comment section",
    "alt": "edgelord meme card reading: the confidence of a person who has read the whole comment section",
    "tags": [
      "edgelord",
      "wordplay",
      "text_post",
      "aggressive"
    ],
    "bg": "#9be8bf",
    "fg": "#141413",
    "ac": "#F26B4E",
    "likes": 259,
    "laughs": 215
  },
  {
    "id": "mk122",
    "topic": "life",
    "text": "i have been “almost ready” to post this for eleven minutes",
    "alt": "self defeating meme card reading: i have been “almost ready” to post this for eleven minutes",
    "tags": [
      "self_defeating",
      "meta",
      "screenshot",
      "self_defeating"
    ],
    "bg": "#C8A8F0",
    "fg": "#141413",
    "ac": "#EFE9DA",
    "likes": 844,
    "laughs": 500
  }
] as const;
