import type {
  Candidate,
  FeedPost,
  Fingerprint,
  Match,
  NotificationItem,
} from "./types";

/* ── gradient library (photo/art placeholder tiles only — never chrome) ── */
export const GRADIENTS = [
  "linear-gradient(135deg, #7c5cff 0%, #b14bff 52%, #2b1e66 100%)",
  "linear-gradient(150deg, #22d3ee 0%, #4f46e5 55%, #161a2e 100%)",
  "linear-gradient(135deg, #a78bfa 0%, #6d28d9 55%, #1e1b4b 100%)",
  "linear-gradient(160deg, #67e8f9 0%, #7c5cff 55%, #2e1065 100%)",
  "radial-gradient(circle at 30% 20%, #c4b5fd 0%, #7c5cff 50%, #171436 100%)",
  "linear-gradient(145deg, #22d3ee 0%, #a855f7 100%)",
  "linear-gradient(135deg, #34d399 0%, #0ea5e9 100%)",
  "linear-gradient(160deg, #f0abfc 0%, #22d3ee 100%)",
  "linear-gradient(135deg, #7c5cff 0%, #ec4899 58%, #1e1b4b 100%)",
  "linear-gradient(140deg, #5eead4 0%, #818cf8 100%)",
  "linear-gradient(135deg, #ddd6fe 0%, #93c5fd 100%)",
  "radial-gradient(circle at 70% 15%, #f472b6 0%, #e879f9 35%, #6d28d9 100%)",
  "linear-gradient(130deg, #fde68a 0%, #f0abfc 100%)",
  "linear-gradient(150deg, #4c1d95 0%, #0891b2 100%)",
] as const;

const A = (i: number) => GRADIENTS[i % GRADIENTS.length];

/* ─────────────────────────── candidates ─────────────────────────── */
export const candidates: Candidate[] = [
  {
    id: "c1",
    name: "Maya",
    age: 26,
    distanceKm: 2.4,
    city: "Brooklyn, NY",
    tasteScore: 87,
    sharedArtist: "Fred again..",
    sharedMemeCategory: "absurdist",
    photoGradient: A(8),
    verified: true,
    lookingFor: "dating",
    blurb:
      "Playlist archivist. Will defend hyperpop in a divot bar. Looking for someone who sends memes instead of good mornings.",
    humor: { affiliative: 0.82, selfEnhancing: 0.64, aggressive: 0.18, selfDefeating: 0.29 },
    humorSummary: "leans affiliative and self-enhancing",
    topArtists: [
      { name: "Fred again..", tag: "uk garage", gradient: A(0) },
      { name: "SZA", tag: "alt r&b", gradient: A(4) },
      { name: "Jamie xx", tag: "electronic", gradient: A(3) },
      { name: "Laufey", tag: "jazz pop", gradient: A(10) },
      { name: "Charli xcx", tag: "hyperpop", gradient: A(5) },
    ],
    playlists: [
      { id: "pl1", title: "brat summer, extended", trackCount: 42, pinned: true },
      { id: "pl2", title: "2am walk home", trackCount: 18, pinned: true },
      { id: "pl3", title: "kitchen disco", trackCount: 27, pinned: true },
    ],
    recentMemes: [
      { id: "m1", gradient: A(4), caption: "the algorithm knows me better than my ex" },
      { id: "m2", gradient: A(9), caption: "one more episode (it is 4am)" },
      { id: "m3", gradient: A(7), caption: "my last two brain cells arguing" },
      { id: "m4", gradient: A(1), caption: "reply guy but for venue openers" },
      { id: "m5", gradient: A(11), caption: "romanticizing my commute again" },
    ],
    prompts: [
      { id: "p1", prompt: "A movie I'll defend to the death", answer: "Paddington 2. It is a heist film." },
      { id: "p2", prompt: "My most-played song when I was 16", answer: "212 — Azealia Banks. No notes." },
      { id: "p3", prompt: "The bit I keep repeating", answer: "Narrating my coffee like a nature documentary." },
    ],
    mutual: true,
  },
  {
    id: "c2",
    name: "Dev",
    age: 28,
    distanceKm: 4.1,
    city: "Queens, NY",
    tasteScore: 81,
    sharedArtist: "Kendrick Lamar",
    sharedMemeCategory: "dry humor",
    photoGradient: A(1),
    verified: true,
    lookingFor: "dating",
    blurb:
      "Jazz-head turned synth tinkerer. I make beats nobody asked for and roast people with love.",
    humor: { affiliative: 0.71, selfEnhancing: 0.58, aggressive: 0.24, selfDefeating: 0.33 },
    humorSummary: "leans affiliative with a dry edge",
    topArtists: [
      { name: "Kendrick Lamar", tag: "west coast hip hop", gradient: A(2) },
      { name: "Kaytranada", tag: "future beats", gradient: A(5) },
      { name: "Hiatus Kaiyote", tag: "neo soul", gradient: A(6) },
      { name: "Mk.gee", tag: "alt guitar", gradient: A(13) },
      { name: "J Dilla", tag: "instrumental hip hop", gradient: A(8) },
    ],
    playlists: [
      { id: "pl4", title: "bus window scholar", trackCount: 31, pinned: true },
      { id: "pl5", title: "sunday vinyl only", trackCount: 12, pinned: true },
      { id: "pl6", title: "gym, but make it dramatic", trackCount: 24, pinned: false },
    ],
    recentMemes: [
      { id: "m6", gradient: A(12), caption: "replying 'this' instead of laughing" },
      { id: "m7", gradient: A(3), caption: "me explaining the lore to someone who asked once" },
      { id: "m8", gradient: A(0), caption: "shipping my friends like it's a series finale" },
      { id: "m9", gradient: A(7), caption: "the group chat civil war" },
      { id: "m10", gradient: A(10), caption: "acting normal about a lineup drop" },
    ],
    prompts: [
      { id: "p4", prompt: "A movie I'll defend to the death", answer: "Ocean's Eleven is a comfort film." },
      { id: "p5", prompt: "My most-played song when I was 16", answer: "Swimming Pools. I peaked early." },
      { id: "p6", prompt: "The bit I keep repeating", answer: "Calling every snack 'a little guy'." },
    ],
    mutual: false,
  },
  {
    id: "c3",
    name: "Sofía",
    age: 25,
    distanceKm: 1.2,
    city: "Lower East Side, NY",
    tasteScore: 92,
    sharedArtist: "Bad Bunny",
    sharedMemeCategory: "wholesome",
    photoGradient: A(4),
    verified: true,
    lookingFor: "dating",
    blurb:
      "Reggaeton apologist, museum serial, amateur bread scientist. My humor is 90% callback.",
    humor: { affiliative: 0.88, selfEnhancing: 0.7, aggressive: 0.12, selfDefeating: 0.2 },
    humorSummary: "leans affiliative and warm",
    topArtists: [
      { name: "Bad Bunny", tag: "reggaeton", gradient: A(8) },
      { name: "ROSALÍA", tag: "flamenco pop", gradient: A(0) },
      { name: "Khruangbin", tag: "psych rock", gradient: A(1) },
      { name: "Karol G", tag: "latin pop", gradient: A(5) },
      { name: "Tame Impala", tag: "psych pop", gradient: A(7) },
    ],
    playlists: [
      { id: "pl7", title: "sandía season", trackCount: 36, pinned: true },
      { id: "pl8", title: "museum pace", trackCount: 15, pinned: true },
      { id: "pl9", title: "perreo for one", trackCount: 22, pinned: false },
    ],
    recentMemes: [
      { id: "m11", gradient: A(5), caption: "screaming into the group chat, respectfully" },
      { id: "m12", gradient: A(11), caption: "my bread starter and I have beef" },
      { id: "m13", gradient: A(2), caption: "acts of service, but it's queuing a playlist" },
      { id: "m14", gradient: A(6), caption: "green flags look boring on paper" },
      { id: "m15", gradient: A(9), caption: "she's just like me, fr" },
    ],
    prompts: [
      { id: "p7", prompt: "A movie I'll defend to the death", answer: "The Devil Wears Prada is documentary fiction." },
      { id: "p8", prompt: "My most-played song when I was 16", answer: "Dákiti on repeat, no apologies." },
      { id: "p9", prompt: "The bit I keep repeating", answer: "Pronouncing 'genre' differently every time." },
    ],
    mutual: true,
  },
  {
    id: "c4",
    name: "Jonah",
    age: 27,
    distanceKm: 6.8,
    city: "Bushwick, NY",
    tasteScore: 74,
    sharedArtist: "Phoebe Bridgers",
    sharedMemeCategory: "self-deprecating",
    photoGradient: A(3),
    verified: false,
    lookingFor: "friends",
    blurb:
      "Record-store clerk energy. I'll make you a mixtape and then never mention it again.",
    humor: { affiliative: 0.55, selfEnhancing: 0.48, aggressive: 0.2, selfDefeating: 0.66 },
    humorSummary: "leans self-defeating, oddly charming",
    topArtists: [
      { name: "Phoebe Bridgers", tag: "indie folk", gradient: A(10) },
      { name: "Big Thief", tag: "indie rock", gradient: A(13) },
      { name: "Adrianne Lenker", tag: "singer songwriter", gradient: A(6) },
      { name: "Japanese Breakfast", tag: "indie pop", gradient: A(4) },
      { name: "Bon Iver", tag: "folktronica", gradient: A(1) },
    ],
    playlists: [
      { id: "pl10", title: "cry in the commuter rail", trackCount: 19, pinned: true },
      { id: "pl11", title: "B-sides only", trackCount: 33, pinned: false },
      { id: "pl12", title: "opening act energy", trackCount: 14, pinned: true },
    ],
    recentMemes: [
      { id: "m16", gradient: A(7), caption: "me, googling symptoms of being perceived" },
      { id: "m17", gradient: A(12), caption: "romanticizing burnout since 2014" },
      { id: "m18", gradient: A(0), caption: "my journal is a group chat" },
      { id: "m19", gradient: A(3), caption: "left on read by the barista (affectionate)" },
      { id: "m20", gradient: A(8), caption: "touch grass, touch vinyl, touch both" },
    ],
    prompts: [
      { id: "p10", prompt: "A movie I'll defend to the death", answer: "Paterson. It's just vibes, and that's cinema." },
      { id: "p11", prompt: "My most-played song when I was 16", answer: "Holocene on a cracked iPod." },
      { id: "p12", prompt: "The bit I keep repeating", answer: "Saying 'as a treat' to justify everything." },
    ],
    mutual: false,
  },
  {
    id: "c5",
    name: "Aisha",
    age: 24,
    distanceKm: 3.3,
    city: "Harlem, NY",
    tasteScore: 84,
    sharedArtist: "Steve Lacy",
    sharedMemeCategory: "chaotic",
    photoGradient: A(5),
    verified: true,
    lookingFor: "dating",
    blurb:
      "Film photo gremlin. My close friends' story is a documentary at this point.",
    humor: { affiliative: 0.76, selfEnhancing: 0.72, aggressive: 0.3, selfDefeating: 0.25 },
    humorSummary: "leans self-enhancing and playful",
    topArtists: [
      { name: "Steve Lacy", tag: "alt r&b", gradient: A(8) },
      { name: "Frank Ocean", tag: "alternative r&b", gradient: A(7) },
      { name: "FKA twigs", tag: "art pop", gradient: A(5) },
      { name: "Daniel Caesar", tag: "r&b", gradient: A(4) },
      { name: "Erykah Badu", tag: "neo soul", gradient: A(1) },
    ],
    playlists: [
      { id: "pl13", title: "golden hour delay", trackCount: 28, pinned: true },
      { id: "pl14", title: "roll, develop, repeat", trackCount: 11, pinned: true },
      { id: "pl15", title: "soft launch", trackCount: 20, pinned: false },
    ],
    recentMemes: [
      { id: "m21", gradient: A(9), caption: "villain origin era (affectionate)" },
      { id: "m22", gradient: A(2), caption: "my camera roll is 90% signs" },
      { id: "m23", gradient: A(6), caption: "running late as a personality" },
      { id: "m24", gradient: A(11), caption: "main character on the L train" },
      { id: "m25", gradient: A(13), caption: "no thoughts, just groove" },
    ],
    prompts: [
      { id: "p13", prompt: "A movie I'll defend to the death", answer: "Moonlight. Every frame is a photograph." },
      { id: "p14", prompt: "My most-played song when I was 16", answer: "Bad Habit. I yelled the bridge." },
      { id: "p15", prompt: "The bit I keep repeating", answer: "Naming every pigeon I see." },
    ],
    mutual: false,
  },
  {
    id: "c6",
    name: "Theo",
    age: 29,
    distanceKm: 8.6,
    city: "Jersey City, NJ",
    tasteScore: 69,
    sharedArtist: "Radiohead",
    sharedMemeCategory: "surreal",
    photoGradient: A(13),
    verified: true,
    lookingFor: "dating",
    blurb:
      "Bass player, bad cook, good curators of memes. Will drive for the right show.",
    humor: { affiliative: 0.6, selfEnhancing: 0.52, aggressive: 0.36, selfDefeating: 0.4 },
    humorSummary: "balanced with a sarcastic tilt",
    topArtists: [
      { name: "Radiohead", tag: "art rock", gradient: A(1) },
      { name: "King Krule", tag: "lo-fi jazz", gradient: A(13) },
      { name: "The Smile", tag: "art rock", gradient: A(3) },
      { name: "Fontaines D.C.", tag: "post punk", gradient: A(2) },
      { name: "Black Midi", tag: "experimental rock", gradient: A(8) },
    ],
    playlists: [
      { id: "pl16", title: "bass face", trackCount: 26, pinned: true },
      { id: "pl17", title: "tunnel to the show", trackCount: 17, pinned: false },
      { id: "pl18", title: "2000s indie canon", trackCount: 45, pinned: true },
    ],
    recentMemes: [
      { id: "m26", gradient: A(0), caption: "my band has a new single (it doesn't)" },
      { id: "m27", gradient: A(5), caption: "arguing about kick drums at dinner" },
      { id: "m28", gradient: A(10), caption: "loading screen personality" },
      { id: "m29", gradient: A(7), caption: "screenshotting to remember jokes" },
      { id: "m30", gradient: A(4), caption: "one more pint becomes a TED talk" },
    ],
    prompts: [
      { id: "p16", prompt: "A movie I'll defend to the death", answer: "Almost Famous, obviously." },
      { id: "p17", prompt: "My most-played song when I was 16", answer: "Fake Plastic Trees, badly." },
      { id: "p18", prompt: "The bit I keep repeating", answer: "Saying 'it's a texture thing' about food." },
    ],
    mutual: false,
  },
  {
    id: "c7",
    name: "Priya",
    age: 27,
    distanceKm: 5.0,
    city: "Astoria, NY",
    tasteScore: 90,
    sharedArtist: "Laufey",
    sharedMemeCategory: "wholesome",
    photoGradient: A(10),
    verified: true,
    lookingFor: "dating",
    blurb:
      "Classically trained, chronically joking. I rate espresso martinis like wine.",
    humor: { affiliative: 0.84, selfEnhancing: 0.66, aggressive: 0.14, selfDefeating: 0.27 },
    humorSummary: "leans affiliative and quick-witted",
    topArtists: [
      { name: "Laufey", tag: "jazz pop", gradient: A(4) },
      { name: "NewJeans", tag: "k-pop", gradient: A(5) },
      { name: "Raveena", tag: "indie r&b", gradient: A(0) },
      { name: "FINNEAS", tag: "pop", gradient: A(10) },
      { name: "Rex Orange County", tag: "indie pop", gradient: A(7) },
    ],
    playlists: [
      { id: "pl19", title: "wine uncle jazz", trackCount: 30, pinned: true },
      { id: "pl20", title: "auntie's cassette shelf", trackCount: 21, pinned: true },
      { id: "pl21", title: "main character metrocard", trackCount: 16, pinned: false },
    ],
    recentMemes: [
      { id: "m31", gradient: A(6), caption: "being normal about a good cappuccino" },
      { id: "m32", gradient: A(11), caption: "my filter bubble is a sitcom" },
      { id: "m33", gradient: A(2), caption: "extrovert with an introvert bedtime" },
      { id: "m34", gradient: A(9), caption: "playlist as a love language" },
      { id: "m35", gradient: A(12), caption: "two hours of laughing at nothing" },
    ],
    prompts: [
      { id: "p19", prompt: "A movie I'll defend to the death", answer: "Crazy Rich Asians is a romcom opera." },
      { id: "p20", prompt: "My most-played song when I was 16", answer: "A Sky Full of Stars, in traffic." },
      { id: "p21", prompt: "The bit I keep repeating", answer: "Rating everything out of five like a critic." },
    ],
    mutual: true,
  },
  {
    id: "c8",
    name: "Lucas",
    age: 26,
    distanceKm: 11.2,
    city: "Bronx, NY",
    tasteScore: 77,
    sharedArtist: "Kaytranada",
    sharedMemeCategory: "absurdist",
    photoGradient: A(6),
    verified: false,
    lookingFor: "friends",
    blurb:
      "Salsa + house in the same set. If the bus has AUX, it's a night out.",
    humor: { affiliative: 0.74, selfEnhancing: 0.6, aggressive: 0.28, selfDefeating: 0.3 },
    humorSummary: "leans affiliative and mischievous",
    topArtists: [
      { name: "Kaytranada", tag: "future beats", gradient: A(5) },
      { name: "Buena Vista Social Club", tag: "son cubano", gradient: A(12) },
      { name: "Disclosure", tag: "uk garage", gradient: A(3) },
      { name: "Rosalía", tag: "flamenco pop", gradient: A(8) },
      { name: "Jungle", tag: "nu disco", gradient: A(1) },
    ],
    playlists: [
      { id: "pl22", title: "bus AUX diplomacy", trackCount: 25, pinned: true },
      { id: "pl23", title: "3am salsa", trackCount: 18, pinned: true },
      { id: "pl24", title: "cook-off soundtrack", trackCount: 23, pinned: false },
    ],
    recentMemes: [
      { id: "m36", gradient: A(3), caption: "gaslight, gatekeep, group chat" },
      { id: "m37", gradient: A(8), caption: "my orbit is a playlist order" },
      { id: "m38", gradient: A(10), caption: "dancing to diagnose my feelings" },
      { id: "m39", gradient: A(0), caption: "extending happy hour as a sport" },
      { id: "m40", gradient: A(6), caption: "corny? yes. sincere? extremely." },
    ],
    prompts: [
      { id: "p22", prompt: "A movie I'll defend to the death", answer: "Step Up. I will not be debating." },
      { id: "p23", prompt: "My most-played song when I was 16", answer: "Latch — the whole bus knew it." },
      { id: "p24", prompt: "The bit I keep repeating", answer: "Explaining 4/4 like it's a discovery." },
    ],
    mutual: false,
  },
];

/* ─────────────────────────── feed posts ─────────────────────────── */
const basePosts: FeedPost[] = [
  {
    id: "drop-0",
    type: "drop",
    author: "Cultured Editors",
    authorGradient: A(8),
    location: "Daily Drop",
    timeAgo: "this morning",
    caption: "Today's pairing: a group-chat classic + a track that fixes posture.",
    memeTop: "POV: you said 'one meme' 40 minutes ago",
    memeBottom: "the chat is at 1,204 and rising",
    trackTitle: "places to be",
    trackArtist: "Fred again..",
    likeCount: 1284,
    laughCount: 640,
    commentCount: 96,
    gradient: A(8),
  },
  {
    id: "f1",
    type: "meme",
    author: "Maya",
    authorGradient: A(8),
    location: "Brooklyn, NY",
    timeAgo: "12m",
    caption: "sent this to the wrong chat and it still landed",
    memeTop: "me: I'm going to be so normal about the lineup",
    memeBottom: "also me, 0.3 seconds later: AAAAA",
    likeCount: 4512,
    laughCount: 2210,
    commentCount: 50,
    gradient: A(4),
    humorTag: "affiliative",
  },
  {
    id: "f2",
    type: "track",
    author: "Dev",
    authorGradient: A(1),
    location: "Queens, NY",
    timeAgo: "28m",
    caption: "This one's bass line is a personality test.",
    trackTitle: "Lite Spots",
    trackArtist: "KAYTRANADA",
    nearbyCount: 3,
    likeCount: 890,
    laughCount: 42,
    commentCount: 31,
    gradient: A(5),
  },
  {
    id: "f3",
    type: "meme",
    author: "Sofía",
    authorGradient: A(4),
    location: "Lower East Side, NY",
    timeAgo: "41m",
    caption: "it's a lifestyle, not a joke",
    memeTop: "my last two brain cells on a Monday:",
    memeBottom: "one is singing, one is filing a complaint",
    likeCount: 7302,
    laughCount: 5120,
    commentCount: 148,
    gradient: A(9),
    humorTag: "self-enhancing",
  },
  {
    id: "f4",
    type: "meme",
    author: "Jonah",
    authorGradient: A(3),
    location: "Bushwick, NY",
    timeAgo: "1h",
    caption: "the Venn diagram is a circle",
    memeTop: "people who say 'we should hang out'",
    memeBottom: "people who own a record player",
    likeCount: 2140,
    laughCount: 1155,
    commentCount: 64,
    gradient: A(10),
    humorTag: "self-defeating",
  },
  {
    id: "f5",
    type: "track",
    author: "Aisha",
    authorGradient: A(5),
    location: "Harlem, NY",
    timeAgo: "1h",
    caption: "Golden-hour fuel. No skips, I don't make the rules.",
    trackTitle: "Bad Habit",
    trackArtist: "Steve Lacy",
    nearbyCount: 7,
    likeCount: 1903,
    laughCount: 88,
    commentCount: 72,
    gradient: A(12),
  },
  {
    id: "f-disc",
    type: "discovery",
    author: "Near you",
    authorGradient: A(6),
    location: "0.8 km away",
    timeAgo: "live",
    caption: "3 people near you liked this exact meme",
    memeTop: "romanticizing my commute like it's cinema",
    memeBottom: "tracking shot on the G train",
    likeCount: 3,
    laughCount: 0,
    commentCount: 0,
    gradient: A(7),
  },
  {
    id: "f6",
    type: "meme",
    author: "Priya",
    authorGradient: A(10),
    location: "Astoria, NY",
    timeAgo: "2h",
    caption: "this account knows too much about me",
    memeTop: "one more episode (it is 4am and I have a 9am)",
    memeBottom: "the episode:",
    likeCount: 9211,
    laughCount: 6604,
    commentCount: 233,
    gradient: A(1),
    humorTag: "affiliative",
  },
  {
    id: "f7",
    type: "track",
    author: "Theo",
    authorGradient: A(13),
    location: "Jersey City, NJ",
    timeAgo: "3h",
    caption: "If this doesn't move your shoulders, check your pulse.",
    trackTitle: "212",
    trackArtist: "Azealia Banks",
    nearbyCount: 2,
    likeCount: 654,
    laughCount: 30,
    commentCount: 18,
    gradient: A(3),
  },
  {
    id: "f8",
    type: "meme",
    author: "Aisha",
    authorGradient: A(5),
    location: "Harlem, NY",
    timeAgo: "4h",
    caption: "kindly, this is an invitation",
    memeTop: "replying 'this' instead of laughing",
    memeBottom: "respectfully: THIS",
    likeCount: 3401,
    laughCount: 1990,
    commentCount: 45,
    gradient: A(11),
    humorTag: "dry humor",
  },
  {
    id: "f9",
    type: "meme",
    author: "Dev",
    authorGradient: A(1),
    location: "Queens, NY",
    timeAgo: "5h",
    caption: "a documentary, really",
    memeTop: "me explaining the lore to someone who asked once",
    memeBottom: "slide 47 of 300",
    likeCount: 5110,
    laughCount: 3320,
    commentCount: 112,
    gradient: A(0),
    humorTag: "absurdist",
  },
  {
    id: "f10",
    type: "track",
    author: "Priya",
    authorGradient: A(10),
    location: "Astoria, NY",
    timeAgo: "6h",
    caption: "Cello go brrr. This is my whole commute now.",
    trackTitle: "Valentine",
    trackArtist: "Laufey",
    nearbyCount: 5,
    likeCount: 2788,
    laughCount: 121,
    commentCount: 90,
    gradient: A(4),
  },
  {
    id: "f11",
    type: "meme",
    author: "Sofía",
    authorGradient: A(4),
    location: "Lower East Side, NY",
    timeAgo: "7h",
    caption: "we're all just out here, fr",
    memeTop: "green flags look boring on paper",
    memeBottom: "genuinely: give me the spreadsheet",
    likeCount: 6040,
    laughCount: 4410,
    commentCount: 176,
    gradient: A(6),
    humorTag: "wholesome",
  },
  {
    id: "f12",
    type: "track",
    author: "Lucas",
    authorGradient: A(6),
    location: "Bronx, NY",
    timeAgo: "8h",
    caption: "Bus AUX diplomacy 101 — start here.",
    trackTitle: "Grow Up",
    trackArtist: "Jungle",
    nearbyCount: 4,
    likeCount: 1122,
    laughCount: 55,
    commentCount: 27,
    gradient: A(13),
  },
  {
    id: "f13",
    type: "meme",
    author: "Maya",
    authorGradient: A(8),
    location: "Brooklyn, NY",
    timeAgo: "9h",
    caption: "she's just like me, for real",
    memeTop: "villain origin era (affectionate)",
    memeBottom: "the villainy: making playlists for strangers",
    likeCount: 8102,
    laughCount: 5904,
    commentCount: 201,
    gradient: A(2),
    humorTag: "self-enhancing",
  },
  {
    id: "f14",
    type: "meme",
    author: "Jonah",
    authorGradient: A(3),
    location: "Bushwick, NY",
    timeAgo: "10h",
    caption: "it's called branding",
    memeTop: "touch grass, touch vinyl, touch both",
    memeBottom: "the grass is next to my turntable",
    likeCount: 1855,
    laughCount: 940,
    commentCount: 39,
    gradient: A(7),
    humorTag: "surreal",
  },
];

/** Infinite feed: deterministic batches, ids vary per cycle. */
export function getFeedBatch(cursor: number, size = 5): { posts: FeedPost[]; next: number } {
  const posts: FeedPost[] = [];
  const cycle = Math.floor(cursor / basePosts.length);
  for (let i = 0; i < size; i++) {
    const idx = (cursor + i) % basePosts.length;
    const p = basePosts[idx];
    posts.push(cycle === 0 ? p : { ...p, id: `${p.id}--c${cycle}` });
  }
  return { posts, next: cursor + size };
}

export const dailyDrop = basePosts[0];

/* ─────────────────────────── my fingerprint ─────────────────────────── */
export const myFingerprint: Fingerprint = {
  humor: { affiliative: 0.78, selfEnhancing: 0.66, aggressive: 0.22, selfDefeating: 0.31 },
  summary: "leans affiliative and self-enhancing",
  topArtists: [
    { name: "Fred again..", tag: "uk garage", gradient: A(0) },
    { name: "SZA", tag: "alt r&b", gradient: A(4) },
    { name: "Bad Bunny", tag: "reggaeton", gradient: A(8) },
    { name: "Jamie xx", tag: "electronic", gradient: A(3) },
    { name: "Laufey", tag: "jazz pop", gradient: A(10) },
  ],
  genres: ["indie sleaze", "hyperpop", "neo soul", "reggaeton", "shoegaze", "drum & bass"],
  playlists: [
    { id: "my1", title: "main character commute", trackCount: 38, pinned: true },
    { id: "my2", title: "kitchen at midnight", trackCount: 22, pinned: true },
    { id: "my3", title: "songs that feel like rain", trackCount: 15, pinned: true },
  ],
  recentMemes: [
    { id: "rm1", gradient: A(4), caption: "the algorithm knows me better than my ex" },
    { id: "rm2", gradient: A(9), caption: "one more episode (it is 4am)" },
    { id: "rm3", gradient: A(7), caption: "romanticizing my commute again" },
    { id: "rm4", gradient: A(1), caption: "reply guy, but for openers" },
    { id: "rm5", gradient: A(11), caption: "my last two brain cells arguing" },
  ],
  prompts: [
    { id: "mp1", prompt: "A movie I'll defend to the death", answer: "Spider-Man: Into the Spider-Verse. Animation changed, sorry." },
    { id: "mp2", prompt: "My most-played song when I was 16", answer: "Midnight City — I thought I was so deep." },
    { id: "mp3", prompt: "The bit I keep repeating", answer: "Calling every tiny dessert 'a little treat for me'." },
  ],
};

export const memeCalibration = [
  { id: "mc1", gradient: A(4), top: "the algorithm knows me better than my ex", bottom: "and honestly? respectful." },
  { id: "mc2", gradient: A(9), top: "replying 'this' instead of laughing", bottom: "respectfully: THIS" },
  { id: "mc3", gradient: A(1), top: "me explaining the lore to someone who asked once", bottom: "slide 47 of 300" },
  { id: "mc4", gradient: A(7), top: "romanticizing my commute like it's cinema", bottom: "tracking shot on the G train" },
  { id: "mc5", gradient: A(6), top: "green flags look boring on paper", bottom: "genuinely: give me the spreadsheet" },
  { id: "mc6", gradient: A(2), top: "villain origin era (affectionate)", bottom: "the villainy: playlists for strangers" },
  { id: "mc7", gradient: A(12), top: "one more episode", bottom: "(it is 4am and I have a 9am)" },
  { id: "mc8", gradient: A(10), top: "my last two brain cells on a Monday:", bottom: "one is singing, one files complaints" },
];

export const musicCalibration = [
  { id: "mc-t1", title: "Delilah (pull me out of this)", artist: "Fred again..", gradient: A(0), vibe: "uk garage" },
  { id: "mc-t2", title: "Kill Bill", artist: "SZA", gradient: A(4), vibe: "alt r&b" },
  { id: "mc-t3", title: "Titi Me Preguntó", artist: "Bad Bunny", gradient: A(8), vibe: "reggaeton" },
  { id: "mc-t4", title: "Awkward", artist: "Steve Lacy", gradient: A(12), vibe: "alt guitar" },
  { id: "mc-t5", title: "From The Start", artist: "Laufey", gradient: A(10), vibe: "jazz pop" },
  { id: "mc-t6", title: "Contact", artist: "KAYTRANADA", gradient: A(5), vibe: "future beats" },
];

export const genreOptions = [
  "indie sleaze", "hyperpop", "neo soul", "reggaeton", "shoegaze",
  "drum & bass", "jazz pop", "afrobeats", "post punk", "synthwave",
  "lo-fi hip hop", "reggae rock", "art pop", "house",
];

/* ─────────────────────────── matches + chat ─────────────────────────── */
export const seedMatches: Match[] = [
  {
    id: "m1",
    candidateId: "c1",
    name: "Maya",
    age: 26,
    gradient: A(8),
    tasteScore: 87,
    city: "Brooklyn, NY",
    mode: "dating",
    matchedOn: {
      kind: "meme",
      title: "the algorithm knows me better than my ex",
      sub: "you both laughed at this",
      gradient: A(4),
    },
    unread: 2,
    lastActive: "now",
    messages: [
      {
        id: "mm1",
        senderId: "them",
        text: "okay important question: is a hot dog a sandwich in your culture",
        time: "9:12 PM",
        reactions: [],
      },
      {
        id: "mm2",
        senderId: "me",
        text: "it's a taco-adjacent treaty. i don't make the rules",
        time: "9:14 PM",
        reactions: ["😂"],
      },
      {
        id: "mm3",
        senderId: "them",
        text: "unhinged. correct. anyway — 87% taste twins says you have to hear this remix",
        time: "9:15 PM",
        reactions: [],
      },
    ],
  },
  {
    id: "m2",
    candidateId: "c7",
    name: "Priya",
    age: 27,
    gradient: A(10),
    tasteScore: 90,
    city: "Astoria, NY",
    mode: "dating",
    matchedOn: {
      kind: "track",
      title: "Valentine — Laufey",
      sub: "you both vibed with this",
      gradient: A(4),
    },
    unread: 0,
    lastActive: "2h",
    messages: [
      {
        id: "mm4",
        senderId: "them",
        text: "your pinned playlist 'kitchen at midnight' is doing a lot of heavy lifting in my week",
        time: "7:41 PM",
        reactions: ["🔥"],
      },
      {
        id: "mm5",
        senderId: "me",
        text: "it's a documented coping strategy at this point",
        time: "7:52 PM",
        reactions: [],
      },
    ],
  },
  {
    id: "m3",
    candidateId: "c2",
    name: "Dev",
    age: 28,
    gradient: A(1),
    tasteScore: 81,
    city: "Queens, NY",
    mode: "friends",
    matchedOn: {
      kind: "meme",
      title: "me explaining the lore to someone who asked once",
      sub: "you both laughed at this",
      gradient: A(0),
    },
    unread: 1,
    lastActive: "1d",
    messages: [
      {
        id: "mm6",
        senderId: "them",
        text: "the slide 47 meme attacked me personally. we should trade mixtapes",
        time: "Yesterday",
        reactions: [],
      },
    ],
  },
];

/* ─────────────────────────── notifications ─────────────────────────── */
export const seedNotifications: NotificationItem[] = [
  {
    id: "n1",
    section: "matches",
    title: "New resonance with Maya",
    body: "You matched over “the algorithm knows me better than my ex”",
    time: "now",
    gradient: A(4),
    unread: true,
  },
  {
    id: "n2",
    section: "matches",
    title: "Priya sent you a track",
    body: "Laufey — From The Start",
    time: "2h",
    gradient: A(10),
    unread: true,
  },
  {
    id: "n3",
    section: "feed",
    title: "Dev commented on your meme",
    body: "“reply guy, but for openers” — “this is targeted”",
    time: "40m",
  },
  {
    id: "n4",
    section: "feed",
    title: "Your Squad remix went up",
    body: "3 remixes of your caption so far",
    time: "3h",
  },
  {
    id: "n5",
    section: "feed",
    title: "Aisha saved your track",
    body: "Steve Lacy — Bad Habit",
    time: "5h",
    gradient: A(12),
  },
  {
    id: "n6",
    section: "fingerprint",
    title: "Your humor profile just got sharper",
    body: "12 new reactions nudged your affiliative bar up a little.",
    time: "1h",
  },
  {
    id: "n7",
    section: "fingerprint",
    title: "Music vector updated",
    body: "Connecting Spotify added 2 new genre tags to your fingerprint.",
    time: "Yesterday",
  },
];

/* ─────────────────────────── misc settings data ─────────────────────────── */
export const antiGenreDefaults = ["country rap", "AI-generated vocals", "aggressive roasts"];
