/**
 * The content layer: typed access to the generated manifests.
 *
 * Everything here is generated by `npm run content:all` and committed, so a
 * fresh clone builds with one command. Nothing is fetched at runtime except
 * music previews, which go through `/api/preview`.
 */

import memeManifest from './memes.manifest.json';
import songManifest from './songs.manifest.json';
import nhieManifest from './nhie.manifest.json';
import type { MemeEntry, MemeManifest, NhieManifest, SongEntry, SongManifest } from './types.ts';

export type { MemeEntry, MemeManifest, NhieManifest, SongEntry, SongManifest };
export type { HumorAxisId, MemeVariant } from './types.ts';

export const memes = memeManifest as unknown as MemeManifest;
export const songs = songManifest as unknown as SongManifest;
export const nhie = nhieManifest as unknown as NhieManifest;

/**
 * Only rights-cleared memes are served to the app. The build gate already
 * fails on unlicensed material, so this is a second line of defence rather
 * than the first — a demo build run under `ALLOW_UNLICENSED=1` still shows
 * them, and says so.
 */
export const servableMemes = (allowUnlicensed = false): MemeEntry[] =>
  allowUnlicensed ? memes.items : memes.items.filter((meme) => meme.rightsCleared);

/** Tracks with a resolvable preview. Unresolved ones are still listed. */
export const playableSongs = (): SongEntry[] => songs.items;

export const resolvedSongs = (): SongEntry[] => songs.items.filter((song) => song.resolved);

export const songById = (id: string): SongEntry | null => songs.items.find((song) => song.id === id) ?? null;

export const memeById = (id: string): MemeEntry | null => memes.items.find((meme) => meme.id === id) ?? null;

/**
 * A playable track for the audio controller, shaped from the manifest.
 * `resolved: false` means the pipeline could not reach a provider, and the UI
 * shows the honest "No preview for this one." line.
 */
export const toPlayable = (song: SongEntry) => ({
  id: song.id,
  title: song.title,
  artist: song.artist,
  previewUrl: song.previewUrl,
  provider: song.provider,
  trackId: song.trackId,
  trackViewUrl: song.trackViewUrl,
  durationMs: song.durationMs,
});

export const contentStats = () => ({
  memes: memes.count,
  songs: songs.count,
  resolvedSongs: songs.resolvedCount,
  nhie: nhie.questions.length,
  nhieRounds: nhie.rounds,
  genres: songs.genres.length,
  categories: memes.categories.length,
});
