/**
 * v5 copy — the typed, single source of UI strings.
 *
 * Generated by hand from `v5Direction/copy_deck.md` (the deck is authoritative;
 * if the two disagree, the deck wins and this file is wrong). Nothing in
 * `src/` should hard-code a user-visible string.
 *
 * Voice rules (enforced in review, not in code):
 *  - Short, dry, self-aware. Complete sentences that end in a period.
 *  - The joke lives in the second sentence.
 *  - No "journey", "unlock", "level up", "find love", "swipe right".
 *  - No exclamation marks except inside reactions.
 *  - Say the real thing: if something is unavailable, say it is unavailable.
 *  - Never a developer word in UI. "Fingerprint clarity", never "signal
 *    confidence"; never "vector", "adapter", "seed", "beat one/two/three".
 */

export const copy = {
  brand: {
    name: 'cultured',
    tagline: 'Match on your humor.',
    antiTagline: 'Not your headshot.',
  },

  intro: {
    lines: ['Match on your humor.', 'Not your headshot.', 'cultured.'] as const,
    ctaPrimary: 'Find my fingerprint',
    ctaSecondary: 'I already have one',
    skip: 'Skip',
  },

  nav: { home: 'Home', arena: 'Arena', matrix: 'Matrix', people: 'People', you: 'You' },

  onboarding: {
    ageGate: {
      headline: 'Grown-ups only.',
      sub: "cultured is 18+. Your birthday is checked on the server and never shown on your profile.",
      cta: 'Looks right',
    },
    underage: {
      headline: 'Come back at 18.',
      sub: "The memes will still be here. They're not going anywhere. They're memes.",
    },
    gauntlet: {
      headline: 'What kind of funny are you?',
      sub: "Swipe right if it's you. Left if it's not. Nothing here is shared.",
      cta: 'swipe',
      milestone4: { headline: 'Okay, I see you.', sub: 'Your fingerprint just got its first ring.' },
      milestone8: { headline: "That's a pattern.", sub: "Whoever you are, you're not boring." },
      done: { headline: 'Twelve for twelve.', sub: 'One more room to check: your ears.', cta: "Let's hear it" },
    },
    genres: {
      headline: 'Pour your taste in.',
      sub: 'Tap what you love until it swells. Up to six.',
      cta: 'Sounds like me',
    },
    soundCheck: {
      headline: 'Three songs. Honest reactions only.',
      sub: 'Thirty seconds each. Your face stays private.',
    },
    signatureLaugh: {
      headline: 'Pick your signature laugh.',
      sub: 'One tap on anything you love sends this. Matches see it on your profile.',
      cta: 'This one',
    },
    nameTag: {
      headline: 'What do people call you?',
      sub: 'A name, not a username. Sixteen characters, no pressure.',
      cta: 'Done',
      maxLength: 16,
    },
    photo: {
      headline: 'Face optional.',
      sub: 'Add one if you want. It stays under your control.',
      cta: 'Add',
      skip: 'Skip for now',
    },
    reveal: {
      headline: 'Your Fingerprint.',
      sub: 'Built from 12 memes, 3 songs and 1 questionable reaction.',
      cta: 'Keep it',
    },
    save: {
      headline: 'Keep your fingerprint.',
      sub: "Sign in so it's still yours tomorrow.",
      email: 'Email me a magic link',
      apple: 'Apple',
      google: 'Google',
    },
    notifications: {
      headline: 'Daily drop at 9:00.',
      sub: 'One song. One meme. Zero small talk.',
      cta: 'Remind me',
      skip: 'Not now',
    },
    location: {
      headline: 'Roughly where you are.',
      sub: 'City-level only. It tunes who shows up near you.',
      cta: 'Allow',
      skip: 'Later',
    },
    tipReact: { headline: 'Hold to react.', sub: 'Long-press anything to pick a reaction.', cta: 'Got it' },
    tipSwipe: { headline: 'Swipe to decide.', sub: 'Right is a laugh. Left is a pass. Up is a save.', cta: 'Got it' },
  },

  home: {
    kicker: "Today's drop, curated for you.",
    deckTitle: 'The Deck',
    deckSub: 'Fifteen laughs a day. Spend them well.',
    laughsLeft: 'Laughs left',
    deckEmpty: {
      headline: "You've seen it all. Impressive and slightly worrying.",
      sub: 'Fresh drops arrive at 9:00.',
    },
    circlesEmpty: {
      headline: "Nobody's online yet. Duel a friend and make some noise.",
      cta: 'Start a duel',
    },
    ritual: "Today's ritual · laugh 3 · save 1 · react once",
    tabs: { receipts: 'Receipts', today: 'Today', draft: 'The Draft', verdict: 'The Verdict', forecast: 'Forecast' },
    galleryCount: (n: number) => `${n} in the gallery`,
  },

  limits: {
    title: 'Laugh budget spent.',
    body: "You've laughed 15 times today. Your cheeks have filed a complaint.",
    sub: 'Saving, passing and sharing are still free. 15 fresh laughs at midnight.',
    cta: 'Back to browsing',
    secondary: 'See what I saved',
    resonates: {
      title: 'Resonates spent for today.',
      body: "New ones at midnight. Your taste isn't going anywhere.",
    },
  },

  placard: {
    format: (n: number, category: string, mood: string) => `Exhibit №${n} · ${category} · Mood: ${mood}`,
    impactLines: [
      'On view since forever. Cultural impact: unforgivable.',
      'Acquired without permission. Displayed with pride.',
      'Please do not touch. Please do react.',
      'Medium: pixels and regret.',
      "Curator's note: yes, this is the one.",
      'Estimated value: priceless. Estimated sense: none.',
      'Last seen causing a group chat to go quiet.',
      'Restored from a screenshot of a screenshot.',
      "Provenance: someone's cousin's phone.",
      'Condition: emotionally damaged, structurally sound.',
    ] as const,
  },

  reactions: {
    meme: {
      '💀': 'Dead',
      '😭': "Can't breathe",
      '🗿': 'Deadpan',
      '🤡': 'Self-own',
      '🧠': 'Galaxy brain',
      '🫠': 'Existential',
      '🥹': 'Soft',
      '🔥': 'Slaps',
    } as Record<string, string>,
    song: {
      '🔥': 'Slaps',
      '🎧': 'On repeat',
      '🥹': 'Soft',
      '😭': 'Wrecked me',
      '🤌': "Chef's kiss",
      '🫠': 'Too real',
      '🕺': 'Moves',
      '💀': 'Dead',
    } as Record<string, string>,
    holdHint: 'Hold for more feelings.',
    combo: (n: number) => (n >= 5 ? 'x5 UNWELL' : `x${n}`),
  },

  vault: {
    title: 'Your Vault. Private. Judged by no one.',
    tabs: { saved: 'Saved', laughed: 'Laughed', pinned: 'Pinned' },
    empty: 'Nothing here yet. Tap the bookmark on anything that gets you.',
    savedToast: 'Kept.',
    unsavedToast: 'Let go.',
    undo: 'Undo',
    pinSheet: 'Pick what matches see first.',
    pinLimit: "That's six. Unpin one to make room.",
    pinBoard: 'Pin board · what they see first.',
    shelf: "On the shelf · songs you'd defend.",
  },

  matrix: {
    cardKicker: (distance: string, intent: string) => `${distance} · ${intent}`,
    compat: {
      tasteTwin: 'Taste twin',
      strong: 'Strong overlap',
      twist: 'Plot twist potential',
      opposites: 'Opposites, loudly',
    },
    resonate: 'Resonate',
    pass: 'Pass',
    resonateOnPin: 'Resonate on this',
    undo: 'Take it back',
    mutual: {
      headline: 'You resonate.',
      sub: 'Two fingerprints, one punchline.',
      sendMeme: 'Send a meme',
      spinOpener: 'Spin an opener',
    },
    emptyQueue: "You've met everyone nearby. Widen the net or come back after the next drop.",
    filters: 'Tune the room',
  },

  people: {
    title: 'People',
    tabs: { chats: 'Chats', stories: 'Stories' },
    emptyChats: {
      body: 'No threads yet. Resonate with someone, then ask them about a song.',
      cta: 'Go to Matrix',
    },
    inputPlaceholder: 'Say something. Or send a meme.',
    quick: { meme: 'Meme', song: 'Song', opener: 'Opener' },
    systemMatch: 'You two resonated. No pressure. Some pressure.',
    typing: '…composing a masterpiece',
  },

  stories: {
    railLabel: 'Stories · gone in 12 hours',
    add: 'Add to story',
    tools: {
      frame: 'Frame',
      backdrop: 'Backdrop',
      stickers: 'Stickers',
      text: 'Text',
      draw: 'Draw',
      filter: 'Filter',
      audience: 'Audience',
    },
    stickers: ['Music', 'Mood', 'W or L', 'Blessed or Cursed', 'Add yours', 'Countdown'] as const,
    audience: ['Everyone', 'Matches', 'Inner circle', 'Hide from…'] as const,
    replyRules: ['Anyone can react', 'Matches can reply', 'Replies off'] as const,
    posted: 'Live for 12 hours.',
    expired: 'Gone. Like it never happened.',
    addYoursPrompts: [
      'Your most replayed shame song',
      'A meme that explains your Monday',
      "The song you'd defend in court",
      'What your 3 AM brain plays',
    ] as const,
    viewers: 'Who saw it',
  },

  sharing: {
    sheetTitle: 'Send it somewhere.',
    targets: ['Story', 'Messages', 'Copy link', 'Save image', 'Match'] as const,
    memeFooter: 'seen on cultured',
    duelResult: 'Damage Report',
    linkCta: 'Find your own fingerprint. Thirty seconds, no photo.',
  },

  arena: {
    header: 'What the room is feeling now.',
    duelTile: 'Same meme, different damage.',
    nhieTile: 'Confess, but funnier.',
    rouletteTile: 'An opener, not "hey".',
    cityMeter: (city: string, n: number) => `${city} unlocks at 100 people. ${n}/100.`,
    roulettePractice: "Practice spin. Nobody's notified.",
    nhie: {
      guilty: 'Guilty',
      clean: 'Clean',
      stampGuilty: 'GUILTY',
      stampClean: 'CLEAN',
      friendReveal: "You're both guilty of:",
      rankTitles: [
        { max: 1, title: 'Suspiciously clean' },
        { max: 4, title: 'Mostly innocent' },
        { max: 7, title: 'A healthy amount of damage' },
        { max: 10, title: 'Repeat offender' },
        { max: 12, title: 'Public menace' },
      ] as const,
    },
  },

  status: {
    loading: [
      'Warming up the memes.',
      'Untangling your fingerprint.',
      'Asking the algorithm nicely.',
      'Polishing the exhibits.',
    ] as const,
    offline: 'No signal. The memes are in a meeting.',
    error: 'That broke. Not you. Try again.',
    noPreview: 'No preview for this one. Open it in Apple Music or Deezer.',
  },

  weekly: {
    slides: [
      'Your week in laughs.',
      '{n} laughs. {m} saves. 1 questionable reaction.',
      'Peak chaos: {time}.',
      'Your most-used reaction: {emoji} {name}.',
      'On repeat: {song}.',
      'You laughed hardest at: {category}.',
      'Your archetype this week: {name}.',
    ] as const,
    caption: 'my week, in memes.',
  },

  forecast: {
    weather: [
      { emoji: '☀️', label: 'Sunny with a chance of delulu' },
      { emoji: '☁️', label: 'Overcast but make it aesthetic' },
      { emoji: '⛈️', label: 'Thunderstorm of group chats' },
      { emoji: '🌫️', label: 'Fog of 3 AM thoughts' },
      { emoji: '🌈', label: 'Suspiciously optimistic' },
      { emoji: '🥶', label: "Do not disturb, I'm recharging" },
    ] as const,
  },

  push: {
    dailyDrop: "Today's drop is live. One song. One meme. Zero small talk.",
    draftWon: "You called it. Tomorrow's drop was your pick.",
    draftLost: 'Not your pick. Still good though.',
    resonance: (pinTitle: string) => `Someone resonated with your ${pinTitle}.`,
    mutual: (name: string) => `You resonate with ${name}. Say something. Or send a meme.`,
    duelReveal: (name: string) => `Your duel with ${name} is in. Brace.`,
    storyReaction: (name: string, emoji: string) => `${name} reacted ${emoji} to your story.`,
    streakAtRisk: 'Your laugh streak ends tonight. One meme saves it.',
    weekly: "Your week is ready. It's a lot.",
  },

  credits: {
    emoji: 'Animated emoji: Noto Emoji Animation by Google, CC BY 4.0.',
  },

  /** Renamed from "signal confidence". Developer words do not reach the UI. */
  fingerprintClarity: 'Fingerprint clarity',
} as const;

/** Compatibility score → label. Thresholds come straight from the copy deck. */
export const compatLabel = (score: number): string => {
  if (score >= 90) return copy.matrix.compat.tasteTwin;
  if (score >= 75) return copy.matrix.compat.strong;
  if (score >= 55) return copy.matrix.compat.twist;
  return copy.matrix.compat.opposites;
};

/** NHIE rank title for a guilty count out of 12. */
export const nhieRank = (guilty: number): string => {
  const clamped = Math.max(0, Math.min(12, guilty));
  for (const band of copy.arena.nhie.rankTitles) if (clamped <= band.max) return band.title;
  return copy.arena.nhie.rankTitles[copy.arena.nhie.rankTitles.length - 1].title;
};

/** A deterministic impact line for a placard, seeded by item id. */
export const impactLine = (seed: string): string => {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i += 1) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return copy.placard.impactLines[Math.abs(h) % copy.placard.impactLines.length];
};
